available_text_models: ["gpt-3.5-turbo", "gpt-4", "text-davinci-003"]

info:
  gpt-3.5-turbo:
    type: chat_completion
    name: GPT-3.5-T
    description: GPT-3.5-Turbo是一个众所周知的模型。它速度<b>快</b>，价格<b>便宜</b>。非常适合日常任务。如果有一些任务它无法处理，请尝试<b>GPT-4</b>。

    price_per_1000_input_tokens: 0.002
    price_per_1000_output_tokens: 0.002

    scores:
      Smart: 3
      Fast: 5
      Cheap: 5

  gpt-4:
    type: chat_completion
    name: GPT-4
    description: GPT-4是世界上最聪明和最先进的模型。但它速度比GPT-3.5-Turbo慢，并且成本效益不如GPT-3.5-Turbo。最适合于<b>复杂的</b>智力任务。

    price_per_1000_input_tokens: 0.03
    price_per_1000_output_tokens: 0.06

    scores:
      Smart: 5
      Fast: 2
      Cheap: 2

  text-davinci-003:
    type: completion
    name: Text-003
    description: Text-davinci-003是一个旧的模型。实际上没有<b>使用它的理由</b>，因为它比GPT-3.5-Turbo更昂贵、更慢，但只是同样聪明。

    price_per_1000_input_tokens: 0.02
    price_per_1000_output_tokens: 0.02

    scores:
      Smart: 3
      Fast: 2
      Cheap: 3

  dalle-2:
     type: image
     price_per_1_image: 0.018  # 512x512

  whisper:
    type: audio
    price_per_1_min: 0.006